// ⚠️ AUTO-GENERATED by generate-theme-aliases.sh — do not edit manually
// Source: src/styles/colors.css

export type ColorName =
	| "background"
	| "foreground"
	| "card"
	| "card-foreground"
	| "popover"
	| "popover-foreground"
	| "primary"
	| "primary-foreground"
	| "secondary"
	| "secondary-foreground"
	| "accent"
	| "accent-foreground"
	| "destructive"
	| "destructive-foreground"
	| "muted"
	| "muted-foreground"
	| "border"
	| "input"
	| "ring"
	| "radius";

export type ColorRecord = Record<ColorName, string>;
